import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./lib/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#0e0e13",
        "outline-variant": "#464554",
        "outline": "#908fa0",
        "surface-variant": "#35343a",
        "on-error": "#690005",
        "surface-tint": "#c0c1ff",
        "secondary-fixed-dim": "#4edea3",
        "surface": "#131318",
        "on-secondary-fixed": "#002113",
        "background": "#131318",
        "secondary": "#4edea3",
        "inverse-on-surface": "#303036",
        "primary-fixed-dim": "#c0c1ff",
        "on-tertiary": "#472a00",
        "on-surface": "#e4e1e9",
        "tertiary-fixed-dim": "#ffb95f",
        "primary": "#c0c1ff",
        "on-secondary": "#003824",
        "surface-container": "#1f1f25",
        "surface-dim": "#131318",
        "primary-container": "#8083ff",
        "on-secondary-container": "#00311f",
        "on-background": "#e4e1e9",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "surface-bright": "#39383e",
        "inverse-surface": "#e4e1e9",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-container-high": "#2a292f",
        "on-primary-fixed": "#07006c",
        "on-surface-variant": "#c7c4d7",
        "secondary-container": "#00a572",
        "on-tertiary-container": "#3e2400",
        "on-secondary-fixed-variant": "#005236",
        "inverse-primary": "#494bd6",
        "tertiary-container": "#ca8100",
        "tertiary": "#ffb95f",
        "primary-fixed": "#e1e0ff",
        "tertiary-fixed": "#ffddb8",
        "on-primary-fixed-variant": "#2f2ebe",
        "surface-container-low": "#1b1b20",
        "secondary-fixed": "#6ffbbe",
        "on-tertiary-fixed": "#2a1700",
        "on-primary": "#1000a9",
        "surface-container-highest": "#35343a",
        "on-primary-container": "#0d0096",
        "error-container": "#93000a",
        // Aliases for specific screens
        "zap-gold": "#fbbf24",
        "zap-amber": "#d97706",
      },
      fontFamily: {
        "headline": ["Instrument Serif", "serif"],
        "body": ["DM Sans", "sans-serif"],
        "kid": ["Nunito", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        "4xl": "2.5rem",
        full: "9999px",
      },
      keyframes: {
        float: {
          "0%,100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-8px)" },
        },
      },
      animation: {
        float: "float 3s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};

export default config;
